master:
  hostname: salt
  build: docker-compose/master
  volumes:
    - .:/srv/salt

ubuntu:
  # Templatized hostnames unavailable until branch is merged.
  # See: https://github.com/docker/compose/pull/1131
  # hostname: ubuntu-%%id%%
  build: docker-compose/child
  links:
    - master
