FROM ubuntu
MAINTAINER Kacey Cole <kcole@izeni.com>

# Fetch system deps
RUN apt-get update && apt-get upgrade -y -o DPkg::Options::=--force-confold

RUN apt-get install -y python-software-properties software-properties-common wget
RUN wget -O - https://repo.saltstack.com/apt/ubuntu/16.04/amd64/latest/SALTSTACK-GPG-KEY.pub | apt-key add -
RUN echo "deb http://repo.saltstack.com/apt/ubuntu/16.04/amd64/latest xenial main" > /etc/apt/sources.list.d/saltstack.list
RUN apt-get update
RUN apt-get install -y salt-master salt-minion salt-ssh salt-syndic
# Remove problematic optional dep.
RUN apt-get remove -y dmidecode

EXPOSE 4505 4506
CMD /usr/bin/salt-master --log-level=error
